version: "3.9"

services:
  api:
    image: public.ecr.aws/p7a4n0s1/transcription-api:latest
    environment:
      DB_URL: ${DB_URL}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "8080:8080"

  nginx:
    image: public.ecr.aws/p7a4n0s1/nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api