version: "3.8"

services:
  api:
    image: public.ecr.aws/p7a4n0s1/transcription-api
    volumes:
      - ./api:/src
    env_file:
      - .env.prod
    environment:
      - ENVIRONMENT=production
    ports:
      - "8080:8080"

  nginx:
    image: public.ecr.aws/p7a4n0s1/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api